//there are like 700 species and it's just gonna clog up my quiz stuff even more so I'm putting them here
//took them from american ornithological society / my brain for some of the shorter ones

let speciesAnatidae = [
    "Black-bellied Whistling-Duck",
    "West Indian Whistling-Duck",
    "Fulvous Whistling-Duck",
    "Emperor Goose",
    "Snow Goose",
    "Ross's Goose",
    "Greater White-fronted Goose",
    "Taiga Bean-Goose",
    "Tundra Bean-Goose",
    "Pink-footed Goose",
    "Brant",
    "Barnacle Goose",
    "Cackling Goose",
    "Canada Goose",
    "Hawaiian Goose",
    "Mute Swan",
    "Trumpeter Swan",
    "Tundra Swan",
    "Whooper Swan",
    "Comb Duck",
    "Egyptian Goose",
    "Ruddy Shelduck",
    "Muscovy Duck",
    "Wood Duck",
    "Blue-winged Teal",
    "Cinnamon Teal",
    "Northern Shoveler",
    "Gadwall",
    "Eurasian Wigeon",
    "American Wigeon",
    "Laysan Duck",
    "Hawaiian Duck",
    "Mallard",
    "Mexican Duck",
    "American Black Duck",
    "Northern Pintail",
    "Green-winged Teal",
    "Canvasback",
    "Redhead",
    "Ring-necked Duck",
    "Tufted Duck",
    "Greater Scaup",
    "Lesser Scaup",
    "Steller's Eider",
    "Spectacled Eider",
    "King Eider",
    "Common Eider",
    "Harlequin Duck",
    "Surf Scoter",
    "White-winged Scoter",
    "Common Scoter",
    "Black Scoter",
    "Long-tailed Duck",
    "Bufflehead",
    "Common Goldeneye",
    "Barrow's Goldeneye",
    "Smew",
    "Hooded Merganser",
    "Common Merganser",
    "Red-breasted Merganser",
    "Ruddy Duck"
  ];


 let speciesOdontophoridae = [ "Tawny-faced Quail",
  "Mountain Quail",
  "Buffy-crowned Wood-Partridge",
  "Long-tailed Wood-Partridge",
  "Bearded Wood-Partridge",
  "Banded Quail",
  "Northern Bobwhite",
  "Black-throated Bobwhite",
  "Spot-bellied Bobwhite",
  "Crested Bobwhite",
  "Scaled Quail",
  "Elegant Quail",
  "California Quail",
  "Gambel's Quail",
  "Montezuma Quail",
  "Ocellated Quail",
  "Singing Quail",
  "Marbled Wood-Quail",
  "Black-eared Wood-Quail",
  "Tacarcuna Wood-Quail",
  "Black-breasted Wood-Quail",
  "Spotted Wood-Quail"];

 let speciesPhasianidae = ["Wild Turkey",  "Ruffed Grouse",
 "Spruce Grouse",
 "Willow Ptarmigan",
 "Rock Ptarmigan",
 "White-tailed Ptarmigan",
 "Greater Sage-Grouse",
 "Gunnison Sage-Grouse",
 "Dusky Grouse",
 "Sooty Grouse",
 "Sharp-tailed Grouse",
 "Greater Prairie-Chicken",
 "Lesser Prairie-Chicken",
 "Gray Partridge",
 "Ring-necked Pheasant",
 "Kalij Pheasant",
 "Indian Peafowl",
 "Gray Francolin",
 "Black Francolin",
 "Red Junglefowl",
 "Himalayan Snowcock",
 "Chukar"];

 let speciesCaprimulgidae = [
    "Short-tailed Nighthawk",
    "Lesser Nighthawk",
    "Common Nighthawk",
    "Antillean Nighthawk",
    "Common Pauraque",
    "Common Poorwill",
    "Jamaican Pauraque",
    "Least Pauraque",
    "Eared Poorwill",
    "Yucatan Poorwill",
    "Ocellated Poorwill",
    "Chuck-will's-widow",
    "Rufous Nightjar",
    "Cuban Nightjar",
    "Hispaniolan Nightjar",
    "Tawny-collared Nightjar",
    "Yucatan Nightjar",
    "Buff-collared Nightjar",
    "Eastern Whip-poor-will",
    "Dusky Nightjar",
    "Mexican Whip-poor-will",
    "Puerto Rican Nightjar",
    "White-tailed Nightjar",
    "Spot-tailed Nightjar"
]

let speciesApodidae = [
    "Black Swift",
    "White-fronted Swift",
    "White-chinned Swift",
    "Spot-fronted Swift",
    "Chestnut-collared Swift",
    "White-collared Swift",
    "White-naped Swift",
    "Gray-rumped Swift",
    "Band-rumped Swift",
    "Costa Rican Swift",
    "Lesser Antillean Swift",
    "Chimney Swift",
    "Vaux's Swift",
    "Chapman's Swift",
    "Sick's Swift",
    "Short-tailed Swift",
    "White-throated Needletail",
    "Mariana Swiftlet",
    "Common Swift",
    "Fork-tailed Swift",
    "Alpine Swift",
    "White-throated Swift"
]

 let speciesTrochilidae = [];

 let speciesCuculidae = ["Greater Ani",
 "Smooth-billed Ani",
 "Groove-billed Ani","Lesser Roadrunner",
 "Greater Roadrunner","Common Cuckoo"];

 let speciesColumbidae = [
    "Rock Pigeon",
    "Common Wood Pigeon",
    "Passenger Pigeon",
    "Pale-vented Pigeon",
    "Scaled Pigeon",
    "Scaly-naped Pigeon",
    "White-crowned Pigeon",
    "Red-billed Pigeon",
    "Plain Pigeon",
    "Band-tailed Pigeon",
    "Ring-tailed Pigeon",
    "Plumbeous Pigeon",
    "Ruddy Pigeon",
    "Short-billed Pigeon",
    "Dusky Pigeon",
    "Oriental Turtle-Dove",
    "African Collared-Dove",
    "European Turtle-Dove",
    "Eurasian Collared-Dove",
    "Spotted Dove",
    "Zebra Dove",
    "Inca Dove",
    "Common Ground Dove",
    "Plain-breasted Ground Dove",
    "Ruddy Ground Dove",
    "Blue Ground Dove",
    "Maroon-chested Ground Dove",
    "Blue-headed Quail-Dove",
    "Crested Quail-Dove",
    "Ruddy Quail-Dove",
    "Violaceous Quail-Dove",
    "Gray-fronted Quail-Dove",
    "White-fronted Quail-Dove",
    "Key West Quail-Dove",
    "Bridled Quail-Dove",
    "Olive-backed Quail-Dove",
    "White-tipped Dove",
    "Caribbean Dove",
    "Gray-chested Dove",
    "Gray-headed Dove",
    "Grenada Dove",
    "Tuxtla Quail-Dove",
    "Buff-fronted Quail-Dove",
    "Purplish-backed Quail-Dove",
    "White-faced Quail-Dove",
    "Chiriqui Quail-Dove",
    "Russet-crowned Quail-Dove", "Mourning Dove"];

 let speciesRallidae = [
    "Spotted Rail",
    "Zapata Rail",
    "Colombian Crake",
    "Paint-billed Crake",
    "Uniform Crake",
    "Rufous-necked Wood-Rail",
    "Russet-naped Wood-Rail",
    "Gray-cowled Wood-Rail",
    "Ridgway's Rail",
    "Aztec Rail",
    "Mangrove Rail",
    "King Rail",
    "Clapper Rail",
    "Virginia Rail",
    "Western Water-Rail",
    "Corn Crake",
    "Sora",
    "Spotted Crake",
    "Common Gallinule",
    "Common Moorhen",
    "Eurasian Coot",
    "Hawaiian Coot",
    "American Coot",
    "Purple Gallinule",
    "Azure Gallinule",
    "Purple Swamphen",
    "Ocellated Crake",
    "Yellow Rail",
    "Yellow-breasted Crake",
    "Ruddy Crake",
    "White-throated Crake",
    "Gray-breasted Crake",
    "Black Rail",
    "Laysan Rail",
    "Hawaiian Rail",
];

let speciesAramidae = ["Limpkin"];
 let speciesGruidae =["Sandhill Crane", "Common Crane", "Whooping Crane"];


 let speciesPodicipedidae = [
    "Least Grebe",
    "Pied-billed Grebe",
    "Atitlan Grebe",
    "Horned Grebe",
    "Red-necked Grebe",
    "Eared Grebe",
    "Western Grebe"
];

// Charadriiformes
let speciesRecurvirostridae = [
    "Black-winged Stilt",
    "Black-necked Stilt",
    "American Avocet"
  ];
  
let speciesHaematopodidae = [
    "Black Oystercatcher",
    "American Oystercatcher"
  ];
  
let speciesCharadriidae = [
    "Black-bellied Plover",
    "European Golden-Plover",
    "American Golden-Plover",
    "Pacific Golden-Plover",
    "Killdeer",
    "Common Ringed Plover",
    "Semipalmated Plover",
    "Piping Plover",
    "Little Ringed Plover",
    "Northern Lapwing",
    "Southern Lapwing",
    "Siberian Sand-Plover",
    "Greater Sand-Plover",
    "Oriental Plover",
    "Wilson's Plover",
    "Collared Plover",
    "Mountain Plover",
    "Snowy Plover"
  ];
  ;
let speciesScolopacidae = [
    "Upland Sandpiper",
    "Bristle-thighed Curlew",
    "Whimbrel",
    "Little Curlew",
    "Eskimo Curlew",
    "Long-billed Curlew",
    "Far Eastern Curlew",
    "Slender-billed Curlew",
    "Bar-tailed Godwit",
    "Black-tailed Godwit",
    "Hudsonian Godwit",
    "Marbled Godwit",
    "Ruddy Turnstone",
    "Black Turnstone",
    "Great Knot",
    "Red Knot",
    "Surfbird",
    "Ruff",
    "Broad-billed Sandpiper",
    "Sharp-tailed Sandpiper",
    "Stilt Sandpiper",
    "Curlew Sandpiper",
    "Temminck's Stint",
    "Long-toed Stint",
    "Spoon-billed Sandpiper",
    "Red-necked Stint",
    "Sanderling",
    "Dunlin",
    "Rock Sandpiper",
    "Purple Sandpiper",
    "Baird's Sandpiper",
    "Little Stint",
    "Least Sandpiper",
    "White-rumped Sandpiper",
    "Buff-breasted Sandpiper",
    "Pectoral Sandpiper",
    "Semipalmated Sandpiper",
    "Western Sandpiper",
    "Short-billed Dowitcher",
    "Long-billed Dowitcher",
    "Jack Snipe",
    "Eurasian Woodcock",
    "American Woodcock",
    "Solitary Snipe",
    "Pin-tailed Snipe",
    "Common Snipe",
    "Wilson's Snipe",
    "Terek Sandpiper",
    "Common Sandpiper",
    "Spotted Sandpiper",
    "Green Sandpiper",
    "Solitary Sandpiper",
    "Gray-tailed Tattler",
    "Wandering Tattler",
    "Lesser Yellowlegs",
    "Willet",
    "Spotted Redshank",
    "Common Greenshank",
    "Greater Yellowlegs",
    "Common Redshank",
    "Wood Sandpiper",
    "Marsh Sandpiper",
    "Wilson's Phalarope",
    "Red-necked Phalarope",
    "Red Phalarope"
  ];
  
let speciesStercorariidae = [
    "Great Skua",
    "South Polar Skua",
    "Pomarine Jaeger",
    "Parasitic Jaeger",
    "Long-tailed Jaeger"
  ];
  
let speciesAlcidae = [
    "Dovekie",
    "Common Murre",
    "Thick-billed Murre",
    "Razorbill",
    "Great Auk",
    "Black Guillemot",
    "Pigeon Guillemot",
    "Long-billed Murrelet",
    "Marbled Murrelet",
    "Kittlitz's Murrelet",
    "Scripps's Murrelet",
    "Guadalupe Murrelet",
    "Craveri's Murrelet",
    "Ancient Murrelet",
    "Cassin's Auklet",
    "Parakeet Auklet",
    "Least Auklet",
    "Whiskered Auklet",
    "Crested Auklet",
    "Rhinoceros Auklet",
    "Atlantic Puffin",
    "Horned Puffin",
    "Tufted Puffin"];
  
let speciesLaridae = [
    "Swallow-tailed Gull",
    "Black-legged Kittiwake",
    "Red-legged Kittiwake",
    "Ivory Gull",
    "Sabine's Gull",
    "Bonaparte's Gull",
    "Gray-hooded Gull",
    "Black-headed Gull",
    "Little Gull",
    "Ross's Gull",
    "Gray Gull",
    "Laughing Gull",
    "Franklin's Gull",
    "Pallas's Gull",
    "Belcher's Gull",
    "Black-tailed Gull",
    "Heermann's Gull",
    "Common Gull",
    "Short-billed Gull",
    "Ring-billed Gull",
    "Western Gull",
    "Yellow-footed Gull",
    "California Gull",
    "Herring Gull",
    "Yellow-legged Gull",
    "Iceland Gull",
    "Lesser Black-backed Gull",
    "Slaty-backed Gull",
    "Glaucous-winged Gull",
    "Glaucous Gull",
    "Great Black-backed Gull",
    "Kelp Gull",
    "Brown Noddy",
    "Black Noddy",
    "Blue-gray Noddy",
    "White Tern",
    "Sooty Tern",
    "Gray-backed Tern",
    "Bridled Tern",
    "Aleutian Tern",
    "Little Tern",
    "Least Tern",
    "Yellow-billed Tern",
    "Large-billed Tern",
    "Gull-billed Tern",
    "Caspian Tern",
    "Inca Tern",
    "Black Tern",
    "White-winged Tern",
    "Whiskered Tern",
    "Roseate Tern",
    "Common Tern",
    "Arctic Tern",
    "Forster's Tern",
    "Royal Tern",
    "Great Crested Tern",
    "Sandwich Tern",
    "Elegant Tern",
    "Black Skimmer"];
  

// Phaethontiformes
let speciesPhaethontidae = [
    "White-tailed Tropicbird",
    "Red-tailed Tropicbird"
  ];
  

// Gaviiformes
let speciesGaviidae = [
    "Red-throated Loon",
    "Arctic Loon",
    "Pacific Loon",
    "Common Loon",
    "Yellow-billed Loon"];
  

// Procellariiformes
let speciesDiomedeidae = [
    "Yellow-nosed Albatross",
    "White-capped Albatross",
    "Chatham Albatross",
    "Salvin's Albatross",
    "Black-browed Albatross",
    "Light-mantled Albatross",
    "Wandering Albatross",
    "Laysan Albatross",
    "Black-footed Albatross",
    "Waved Albatross",
    "Short-tailed Albatross"
  ];
  
let speciesOceanitidae = [
    "Wilson's Storm-Petrel",
    "White-faced Storm-Petrel",
    "Black-bellied Storm-Petrel"
  ];
  
  let speciesHydrobatidae = [
    "European Storm-Petrel",
    "Fork-tailed Storm-Petrel",
    "Ringed Storm-Petrel",
    "Swinhoe's Storm-Petrel",
    "Leach's Storm-Petrel",
    "Townsend's Storm-Petrel",
    "Ainley's Storm-Petrel",
    "Ashy Storm-Petrel",
    "Band-rumped Storm-Petrel",
    "Wedge-rumped Storm-Petrel",
    "Black Storm-Petrel",
    "Guadalupe Storm-Petrel",
    "Markham's Storm-Petrel",
    "Tristram's Storm-Petrel",
    "Least Storm-Petrel"
  ];  

// Ciconiiformes
let speciesCiconiidae = [
  "Maguari Stork",
  "Wood Stork"
];


// Suliformes
let speciesFregatidae = [
  "Lesser Frigatebird",
  "Magnificent Frigatebird"
];

let speciesSulidae = [
  "Masked Booby",
  "Nazca Booby",
  "Blue-footed Booby",
  "Peruvian Booby",
  "Brown Booby",
  "Cocos Booby",
  "Red-footed Booby",
  "Northern Gannet"
];

let speciesAnhingidae = ["Anhinga"];
let speciesPhalacrocoracidae = [
  "Brandt's Cormorant",
  "Red-faced Cormorant",
  "Pelagic Cormorant",
  "Great Cormorant",
  "Double-crested Cormorant"
];


// Pelecaniformes
let speciesPelecanidae = ["American White Pelican", "Brown Pelican"];
let speciesArdeidae = [
  "Least Bittern",
  "American Bittern",
  "Pinnated Bittern",
  "Little Bittern",
  "Yellow Bittern",
  "Little Blue Heron",
  "Tricolored Heron",
  "Reddish Egret",
  "Snowy Egret",
  "Little Egret",
  "Yellow-crowned Night Heron",
  "Black-crowned Night Heron",
  "Green Heron",
  "Great Egret",
  "Medium Egret",
  "Western Cattle-Egret",
  "Eastern Cattle-Egret",
];

// Accipitriformes
let speciesPandionidae = ["Osprey"];
let speciesAccipitridae = [
  "Pearl Kite",
  "White-tailed Kite",
  "Hook-billed Kite",
  "Golden Eagle",
  "Tiny Hawk",
  "Northern Harrier",
  "Sharp-shinned Hawk",
  "Cooper's Hawk",
  "Eurasian Goshawk",
  "American Goshawk",
  "Black Kite",
  "Bald Eagle",
  "White-tailed Eagle",
  "Mississippi Kite",
  "Snail Kite",
  "Slender-billed Kite",
  "Harris's Hawk",
  "White-tailed Hawk",
  "White Hawk",
  "Semiplumbeous Hawk",
  "Gray Hawk",
  "Red-shouldered Hawk",
  "Broad-winged Hawk",
  "Hawaiian Hawk",
  "Short-tailed Hawk",
  "Swainson's Hawk",
  "Zone-tailed Hawk",
  "Red-tailed Hawk",
  "Rough-legged Hawk",
  "Ferruginous Hawk",
  "Long-legged Buzzard"
];

// Strigiformes
let speciesStrigidae = [
  "Flammulated Owl",
  "Puerto Rican Owl",
  "Whiskered Screech-Owl",
  "Bare-shanked Screech-Owl",
  "Western Screech-Owl",
  "Eastern Screech-Owl",
  "Balsas Screech-Owl",
  "Great Horned Owl",
  "Snowy Owl",
  "Northern Hawk Owl",
  "Northern Pygmy-Owl",
  "Elf Owl",
  "Burrowing Owl",
  "Spotted Owl",
  "Barred Owl",
  "Fulvous Owl",
  "Mottled Owl",
  "Great Gray Owl",
  "Long-eared Owl",
  "Short-eared Owl",
  "Striped Owl",
  "Jamaican Owl",
  "Boreal Owl",
  "Northern Saw-whet Owl"
];

// Trogoniformes
let speciesTrogonidae = ["Elegant Trogon", "Resplendent Quetzel"];

// Coraciiformes
let speciesAlcedinidae = ["Belted Kingfisher", "Green Kingfisher", "American Pygmy Kingfisher"];

// Piciformes
let speciesPicidae = [
  "Lewis's Woodpecker",
  "Guadeloupe Woodpecker",
  "Puerto Rican Woodpecker",
  "Red-headed Woodpecker",
  "Acorn Woodpecker",
  "Golden-naped Woodpecker",
  "Black-cheeked Woodpecker",
  "Red-crowned Woodpecker",
  "Gila Woodpecker",
  "Hoffmann's Woodpecker",
  "Golden-fronted Woodpecker",
  "Red-bellied Woodpecker",
  "Williamson's Sapsucker",
  "Yellow-bellied Sapsucker",
  "Red-naped Sapsucker",
  "Red-breasted Sapsucker",
  "American Three-toed Woodpecker",
  "Black-backed Woodpecker",
  "Downy Woodpecker",
  "Nuttall's Woodpecker",
  "Ladder-backed Woodpecker",
  "Red-cockaded Woodpecker",
  "Hairy Woodpecker",
  "White-headed Woodpecker",
  "Smoky-brown Woodpecker",
  "Arizona Woodpecker",
  "Strickland's Woodpecker",
  "Red-rumped Woodpecker",
  "Northern Flicker",
  "Gilded Flicker",
  "Pileated Woodpecker"
];

// Falconiformes
let speciesFalconidae = [
  "Crested Caracara",
  "American Kestrel",
  "Red-footed Falcon",
  "Merlin",
  "Aplomado Falcon",
  "Gyrfalcon",
  "Peregrine Falcon",
  "Prairie Falcon"
];


// Psittaciformes
let speciesPsittacidae = [
  "Painted Parakeet",
  "Sulphur-winged Parakeet",
  "Monk Parakeet",
  "Olive-throated Parakeet",
  "Orange-fronted Parakeet",
  "Nanday Parakeet",
  "Chestnut-fronted Macaw",
  "Scarlet Macaw",
  "Green Parakeet",
  "Socorro Parakeet",
  "Pacific Parakeet",
  "Mitred Parakeet",
  "Red-masked Parakeet",
  "Crimson-fronted Parakeet",
  "White-winged Parakeet",
  "Yellow-chevroned Parakeet",
  "Red-fronted Parrotlet",
  "Blue-fronted Parrotlet",
  "Blue-headed Parrot",
  "White-crowned Parrot",
  "White-fronted Parrot",
  "Yellow-lored Parrot",
  "Yellow-billed Parrot",
  "Lilac-crowned Parrot",
  "Red-lored Parrot",
  "Yellow-headed Parrot",
  "Yellow-naped Parrot",
  "Yellow-crowned Parrot",
  "Red-necked Parrot",
  "St. Lucia Parrot",
  "St. Vincent Parrot",
  "Imperial Parrot"
];

let speciesPsittaculidae = ["Rose-ringed Parakeet", "Rosy-faced Lovebird"];
// Passeriformes
let speciesAegithalidae = ["Bushtit"];
let speciesAlaudidae = ["Horned Lark"];
let speciesBombycillidae = ["Cedar Waxwing", "Bohemian Waxwing"];
let speciesCardinalidae = [
  "Hepatic Tanager",
  "Summer Tanager",
  "Scarlet Tanager",
  "Western Tanager",
  "Black-faced Grosbeak",
  "Northern Cardinal",
  "Pyrrhuloxia",
  "Rose-breasted Grosbeak",
  "Black-headed Grosbeak",
  "Blue Bunting",
  "Blue Grosbeak",
  "Lazuli Bunting",
  "Indigo Bunting",
  "Varied Bunting",
  "Painted Bunting",
  "Dickcissel"

];
let speciesCerthiidae = ["Brown Creeper"];
let speciesCinclidae = ["American Dipper"];
let speciesCorvidae = [
  "Canada Jay",
  "Brown Jay",
  "Green Jay",
  "Pinyon Jay",
  "Steller's Jay",
  "Blue Jay",
  "Florida Scrub-Jay",
  "Island Scrub-Jay",
  "California Scrub-Jay",
  "Woodhouse's Scrub-Jay",
  "Mexican Jay",
  "Clark's Nutcracker",
  "Black-billed Magpie",
  "Yellow-billed Magpie",
  "American Crow",
  "Fish Crow",
  "Hawaiian Crow",
  "Chihuahuan Raven",
  "Common Raven"
];

let speciesEstrildidae = ["Scaly-breasted Munia"];
let speciesFringillidae = [ "American Goldfinch",
"Black Rosy Finch",
"Black-headed Siskin",
"Brown-capped Rosy Finch",
"Cassia Crossbill",
"Cassin's Finch",
"Eurasian Siskin",
"Evening Grosbeak",
"Grey-crowned Rosy Finch",
"House Finch",
"Lawrence's Goldfinch",
"Lesser Goldfinch",
"Pine Grosbeak",
"Pine Siskin",
"Purple Finch",
"Red Crossbill",
"Redpoll",
"Two-barred Crossbill"];
let speciesHirundinidae = ["Bank Swallow", "Tree Swallow", "Violet-green Swallow",
"Northern Rough-winged Swallow", "Purple Martin", "Barn Swallow", "Cliff Swallow", "Cave Swallow"];
let speciesIcteridae = [
  "Yellow-headed Blackbird",
  "Bobolink",
  "Chihuahuan Meadowlark",
  "Eastern Meadowlark",
  "Western Meadowlark",
  "Orchard Oriole",
  "Hooded Oriole",
  "Bullock's Oriole",
  "Orange Oriole",
  "Spot-breasted Oriole",
  "Altamira Oriole",
  "Audubon's Oriole",
  "Baltimore Oriole",
  "Black-backed Oriole",
  "Scott's Oriole",
  "Red-winged Blackbird",
  "Tricolored Blackbird",
  "Shiny Cowbird",
  "Bronzed Cowbird",
  "Brown-headed Cowbird",
  "Giant Cowbird",
  "Rusty Blackbird",
  "Brewer's Blackbird",
  "Common Grackle",
  "Boat-tailed Grackle",
  "Great-tailed Grackle",
  "Yellow-hooded Blackbird"
];

let speciesLaniidae = ["Loggerhead Shrike", "Northern Shrike"];
let speciesMimidae = ["Brown Thrasher", "Curve-billed Thrasher", "Cozumel Thrasher", "Bendire's Thrasher",
"California Thrasher", "LeConte's Thrasher", "Crissal Thrasher", "Sage Thrasher", "Northern Mockingbird"];
let speciesMotacillidae = ["American Pipit"];
let speciesMuscicapidae = ["Northern Wheatear", "Pied Wheatear"];
let speciesParidae = [ "Carolina Chickadee",
"Black-capped Chickadee",
"Mountain Chickadee",
"Mexican Chickadee",
"Chestnut-backed Chickadee",
"Boreal Chickadee",
"Gray-headed Chickadee",
"Bridled Titmouse",
"Oak Titmouse",
"Juniper Titmouse",
"Tufted Titmouse",
"Black-crested Titmouse"];
let speciesParulidae = [
  "Ovenbird",
  "Worm-eating Warbler",
  "Louisiana Waterthrush",
  "Northern Waterthrush",
  "Bachman's Warbler",
  "Golden-winged Warbler",
  "Blue-winged Warbler",
  "Black-and-white Warbler",
  "Prothonotary Warbler",
  "Tennessee Warbler",
  "Orange-crowned Warbler",
  "Colima Warbler",
  "Lucy's Warbler",
  "Nashville Warbler",
  "Virginia's Warbler",
  "Connecticut Warbler",
  "MacGillivray's Warbler",
  "Mourning Warbler",
  "Kentucky Warbler",
  "Common Yellowthroat",
  "Hooded Warbler",
  "American Redstart",
  "Kirtland's Warbler",
  "Cape May Warbler",
  "Cerulean Warbler",
  "Northern Parula",
  "Magnolia Warbler",
  "Bay-breasted Warbler",
  "Blackburnian Warbler",
  "Yellow Warbler",
  "Chestnut-sided Warbler",
  "Blackpoll Warbler",
  "Black-throated Blue Warbler",
  "Palm Warbler",
  "Olive-capped Warbler",
  "Pine Warbler",
  "Yellow-rumped Warbler",
  "Yellow-throated Warbler",
  "Prairie Warbler",
  "Grace's Warbler",
  "Black-throated Gray Warbler",
  "Townsend's Warbler",
  "Hermit Warbler",
  "Golden-cheeked Warbler",
  "Black-throated Green Warbler",
  "Golden-crowned Warbler",
  "Canada Warbler",
  "Wilson's Warbler",
  "Painted Redstart",
];

let speciesPasserellidae = [
    "Savannah Sparrow",
    "LeConte's Sparrow",
    "Seaside Sparrow",
    "Nelson's Sparrow",
    "Saltmarsh Sparrow",
    "Song Sparrow",
    "Lincoln's Sparrow",
    "Swamp Sparrow",
    "Baird's Sparrow",
    "Henslow's Sparrow",
    "Vesper Sparrow",
    "Fox Sparrow",
    "American Tree Sparrow",
    "Dark-eyed Junco",
    "Yellow-eyed Junco",
    "Rufous-collared Sparrow",
    "White-crowned Sparrow",
    "Golden-crowned Sparrow",
    "Harris's Sparrow",
    "White-throated Sparrow",
    "Bell's Sparrow",
    "Sagebrush Sparrow",
    "Striped Sparrow",
    "Lark Sparrow",
    "Lark Bunting",
    "Chipping Sparrow",
    "Clay-colored Sparrow",
    "Black-chinned Sparrow",
    "Field Sparrow",
    "Brewer's Sparrow",
    "Grasshopper Sparrow",
    "Green-backed Sparrow",
    "Black-striped Sparrow",
    "Five-striped Sparrow",
    "Black-throated Sparrow",
    "Rufous-crowned Sparrow",
    "Oaxaca Sparrow",
    "Bachman's Sparrow",
    "Botteri's Sparrow",
    "Cassin's Sparrow",
    "Spotted Towhee",
    "Eastern Towhee",
    "Green-tailed Towhee",
    "Canyon Towhee",
    "California Towhee",
    "Abert's Towhee",
    "Sierra Madre Sparrow",
    "Zapata Sparrow"
];

let speciesPasseridae = ["House Sparrow"];
let speciesPeucedramidae = ["Olive Warbler"];
let speciesPhylloscopidae = ["Willow Warbler", "Dusky Warbler", "Arctic Warbler"];
let speciesPolioptilidae = ["Blue-gray Gnatcatcher", "Black-tailed Gnatcatcher", "California Gnatcatcher", "Black-capped Gnatcatcher"];
let speciesPtiliogonatidae = ["Phainopepla"];
let speciesPycnonotidae = ["Red-whiskered Bulbul"];
let speciesRegulidae = ["Ruby-crowned Kinglet", "Golden-crowned Kinglet"];
let speciesRemizidae = ["Verdin"];
let speciesSittidae = ["Red-breasted Nuthatch", "White-breasted Nuthatch", "Pygmy Nuthatch", "Brown-headed Nuthatch"];
let speciesSpindalidae = ["Western Spindalis"];
let speciesSturnidae = ["European Starling", "Common Myna"];
let speciesTityridae = [
  "Northern Schiffornis", "Russet-winged Schiffornis", "Speckled Mourner", 
  "Masked Tityra", "Black-crowned Tityra", "Barred Becard", "Cinereous Becard", 
  "Cinnamon Becard", "White-winged Becard", "Black-and-white Becard", 
  "Gray-collared Becard", "Rose-throated Becard", "One-colored Becard", 
  "Jamaican Becard"
];
let speciesTroglodytidae = ["Rock Wren", "Canyon Wren", "Cactus Wren", "Bewick's Wren", "Carolina Wren",
"Northern House Wren", "Southern House Wren", "Pacific Wren", "Winter Wren", "Sedge Wren", "Marsh Wren"];
let speciesTurdidae = [
  "Eastern Bluebird", "Western Bluebird", "Mountain Bluebird", 
  "Townsend's Solitaire",
  "Veery", "Gray-cheeked Thrush", "Bicknell's Thrush", "Swainson's Thrush", 
  "Hermit Thrush", "Wood Thrush", "Song Thrush", "Sooty Thrush", "Black Thrush", "Mountain Thrush", 
 "Pale-vented Thrush", "Clay-colored Thrush", "Spectacled Thrush", 
  "White-eyed Thrush", "White-throated Thrush", "Rufous-backed Robin", 
  "Rufous-collared Robin", "American Robin", "La Selle Thrush", 
  "White-chinned Thrush", "Grand Cayman Thrush", "Red-legged Thrush", 
  "Forest Thrush", "Varied Thrush"
];
let speciesTyrannidae = [
  "Dusky-capped Flycatcher",
  "Ash-throated Flycatcher",
  "Nutting's Flycatcher",
  "Great Crested Flycatcher",
  "Great Kiskadee",
  "Cattle Tyrant",
  "Sulphur-bellied Flycatcher",
  "Tropical Kingbird",
  "Couch's Kingbird",
  "Cassin's Kingbird",
  "Thick-billed Kingbird",
  "Western Kingbird",
  "Eastern Kingbird",
  "Gray Kingbird",
  "Loggerhead Kingbird",
  "Giant Kingbird",
  "Scissor-tailed Flycatcher",
  "Fork-tailed Flycatcher",
  "Olive-sided Flycatcher",
  "Western Wood-Pewee",
  "Eastern Wood-Pewee",
  "Yellow-bellied Flycatcher",
  "Acadian Flycatcher",
  "Alder Flycatcher",
  "Willow Flycatcher",
  "Least Flycatcher",
  "Hammond's Flycatcher",
  "Gray Flycatcher",
  "Dusky Flycatcher",
  "Pine Flycatcher",
  "Western Flycatcher",
  "Black-capped Flycatcher",
  "Black Phoebe",
  "Eastern Phoebe",
  "Say's Phoebe",
  "Vermilion Flycatcher",
];

let speciesVireonidae = ["Black-capped Vireo", "White-eyed Vireo", "Bell's Vireo", 
"Gray Vireo", "Hutton's Vireo", "Cassin's Vireo", "Blue-headed Vireo", "Plumbeous Vireo",
"Warbling Vireo", "Red-eyed Vireo", "Black-whiskered Vireo"];


//my export!
export {speciesAnatidae,
    speciesOdontophoridae,
    speciesPhasianidae,
    speciesCaprimulgidae,
    speciesApodidae,
    speciesTrochilidae,
    speciesCuculidae,
    speciesColumbidae,
    speciesRallidae,
    speciesAramidae,
    speciesGruidae,
    speciesPodicipedidae,
    speciesRecurvirostridae,
    speciesHaematopodidae,
    speciesCharadriidae,
    speciesScolopacidae,
    speciesStercorariidae,
    speciesAlcidae,
    speciesLaridae,
    speciesPhaethontidae,
    speciesGaviidae,
    speciesDiomedeidae,
    speciesOceanitidae,
    speciesHydrobatidae,
    speciesCiconiidae,
    speciesFregatidae,
    speciesSulidae,
    speciesAnhingidae,
    speciesPhalacrocoracidae,
    speciesPelecanidae,
    speciesArdeidae,
    speciesPandionidae,
    speciesAccipitridae,
    speciesStrigidae,
    speciesTrogonidae,
    speciesAlcedinidae,
    speciesPicidae,
    speciesFalconidae,
    speciesPsittacidae,
    speciesPsittaculidae,
    speciesAegithalidae,
    speciesAlaudidae,
    speciesBombycillidae,
    speciesCardinalidae,
    speciesCerthiidae,
    speciesCinclidae,
    speciesCorvidae,
    speciesEstrildidae,
    speciesFringillidae,
    speciesHirundinidae,
    speciesIcteridae,
    speciesLaniidae,
    speciesMimidae,
    speciesMotacillidae,
    speciesMuscicapidae,
    speciesParidae,
    speciesParulidae,
    speciesPasserellidae,
    speciesPasseridae,
    speciesPeucedramidae,
    speciesPhylloscopidae,
    speciesPolioptilidae,
    speciesPtiliogonatidae,
    speciesPycnonotidae,
    speciesRegulidae,
    speciesRemizidae,
    speciesSittidae,
    speciesSpindalidae,
    speciesSturnidae,
    speciesTityridae,
    speciesTroglodytidae,
    speciesTurdidae,
    speciesTyrannidae,
    speciesVireonidae
  };
  

  